#cloud-config
package_update: true
packages:
  - ca-certificates
  - curl

write_files:
  - path: /opt/app/docker-compose.yml
    permissions: "0644"
    content: |
      services:
        child-and-me-db:
          image: mudz1212/child-and-me-db-cloud:latest
          restart: always
          volumes:
            - child-and-me-db-data:/var/lib/postgresql/data
          networks:
            - child-and-me-network

        child-and-me-server:
          image: mudz1212/child-and-me-server-cloud:latest
          ports:
            - "80:80"
          restart: always
          depends_on:
            - child-and-me-db
          env_file:
            - .env
          networks:
            - child-and-me-network

      networks:
        child-and-me-network:

      volumes:
        child-and-me-db-data:

runcmd:
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - systemctl enable --now docker
  - usermod -aG docker azureuser
  - touch /opt/app/.env
  - docker compose -f /opt/app/docker-compose.yml up -d
